id: A14B3BB41
base_file: f57BF.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:20:23.213179
  last_modified_at: 2022-06-17 12:20:23.213184
