id: A14B3BB41
base_file: f8BE4.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:20:23.224129
  last_modified_at: 2022-06-17 12:20:23.224132
