id: A14B3BB41
base_file: f8D9A.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:20:23.227683
  last_modified_at: 2022-06-17 12:20:23.227686
