id: A14B3BB41
base_file: f7B41.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:20:23.216308
  last_modified_at: 2022-06-17 12:20:23.216310
