id: A14B3BB41
base_file: f5DBB.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:20:23.215096
  last_modified_at: 2022-06-17 12:20:23.215099
