id: A14B3BB41
base_file: f968D.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:20:23.231496
  last_modified_at: 2022-06-17 12:20:23.231499
