id: A14B3BB41
base_file: f87D7.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:20:23.218112
  last_modified_at: 2022-06-17 12:20:23.218115
